package Vistas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Vistas.*;
import controlador.servicio.PersonaServicio;
import controlador.utilidades.Sesion;
import java.awt.BorderLayout;
import java.awt.Color;
import vista.tabla.ModeloTablaCliente;
import vista.utilidades.Utilitario;

/**
 *
 * @author Usuario
 */
public class FrmClientePrincipal extends javax.swing.JFrame {

    Utilitario u = new Utilitario();
    ModeloTablaCliente modelo = new ModeloTablaCliente();
    private PersonaServicio ps = new PersonaServicio();

    /**
     * Creates new form FrmLogin
     */
    public FrmClientePrincipal() {
        initComponents();
        //jPanel3 .setBackground(new Color(0,0,0,140));
        cargar();
        cargarTabla();
    }

    private void cargarTabla() {
        modelo.setLista(ps.ListarAClientePorCedula(Sesion.getCuenta().getPersona().getCedula()));
        jTable1.setModel(modelo);
        jTable1.updateUI();
    }

    private void cargar() {
        jLabel7.setText(Sesion.getCuenta().getPersona().getApellido() + " " + Sesion.getCuenta().getPersona().getNombre());
        jLabel3.setText(String.valueOf(Sesion.getCuenta().getPersona().getCuentaBancaria().getFechaApertura()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnSesion2 = new rojeru_san.RSButtonRiple();
        btnSesion3 = new rojeru_san.RSButtonRiple();
        btnSesion4 = new rojeru_san.RSButtonRiple();
        btnSesion5 = new rojeru_san.RSButtonRiple();
        jLabel1 = new javax.swing.JLabel();
        btnSesion6 = new rojeru_san.RSButtonRiple();
        panelBienvenido = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        jButton11 = new javax.swing.JButton();
        paneelcoonsolidada = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(10, 125, 108));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(93, 203, 187));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        btnSesion2.setBackground(new java.awt.Color(223, 247, 244));
        btnSesion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-home-page-24.png"))); // NOI18N
        btnSesion2.setText("Principal");
        btnSesion2.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion2.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSesion2);

        btnSesion3.setBackground(new java.awt.Color(223, 247, 244));
        btnSesion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-cash-in-hand-filled-30.png"))); // NOI18N
        btnSesion3.setText("Tranferencia");
        btnSesion3.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion3.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnSesion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion3ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSesion3);

        btnSesion4.setBackground(new java.awt.Color(223, 247, 244));
        btnSesion4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-payment-history-filled-40.png"))); // NOI18N
        btnSesion4.setText("Historial");
        btnSesion4.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion4.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnSesion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion4ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSesion4);

        btnSesion5.setBackground(new java.awt.Color(223, 247, 244));
        btnSesion5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-delete-30.png"))); // NOI18N
        btnSesion5.setText("   Salir");
        btnSesion5.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion5.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion5.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnSesion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion5ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSesion5);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/vinilo-decorativo-arbol-sin-hojas.jpg"))); // NOI18N
        jPanel4.add(jLabel1);

        btnSesion6.setBackground(new java.awt.Color(223, 247, 244));
        btnSesion6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-add-user-male-26.png"))); // NOI18N
        btnSesion6.setText("Registro");
        btnSesion6.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion6.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnSesion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion6ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSesion6);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 570));

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 0, 163, 598);

        panelBienvenido.setBackground(new java.awt.Color(65, 135, 124));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        labelMetric2.setBackground(new java.awt.Color(40, 153, 255));
        labelMetric2.setText("Bienvenido estimado socio(a) :");
        labelMetric2.setColorDeSombra(new java.awt.Color(40, 52, 71));
        labelMetric2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        javax.swing.GroupLayout panelBienvenidoLayout = new javax.swing.GroupLayout(panelBienvenido);
        panelBienvenido.setLayout(panelBienvenidoLayout);
        panelBienvenidoLayout.setHorizontalGroup(
            panelBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBienvenidoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelBienvenidoLayout.setVerticalGroup(
            panelBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBienvenidoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(panelBienvenido);
        panelBienvenido.setBounds(169, 33, 701, 59);

        jButton11.setBackground(new java.awt.Color(84, 178, 164));
        jButton11.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton11.setForeground(new java.awt.Color(102, 102, 102));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-logout-rounded-up-16.png"))); // NOI18N
        jButton11.setText("Cerrar Sesion");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(749, 7, 121, 20);

        paneelcoonsolidada.setBackground(new java.awt.Color(65, 135, 124));
        paneelcoonsolidada.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Posicion Consolidada");

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Descripcion", "Numero de Cuenta", "Saldo Disponible", "Saldo Contable"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(65, 135, 124));
        jTable1.setSelectionBackground(new java.awt.Color(223, 247, 244));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setBackground(new java.awt.Color(0, 0, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cuanta de ahorros");

        javax.swing.GroupLayout paneelcoonsolidadaLayout = new javax.swing.GroupLayout(paneelcoonsolidada);
        paneelcoonsolidada.setLayout(paneelcoonsolidadaLayout);
        paneelcoonsolidadaLayout.setHorizontalGroup(
            paneelcoonsolidadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelcoonsolidadaLayout.createSequentialGroup()
                .addGroup(paneelcoonsolidadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addGroup(paneelcoonsolidadaLayout.createSequentialGroup()
                        .addGroup(paneelcoonsolidadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneelcoonsolidadaLayout.setVerticalGroup(
            paneelcoonsolidadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneelcoonsolidadaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(paneelcoonsolidada);
        paneelcoonsolidada.setBounds(170, 150, 700, 130);

        panelPrincipal.setBackground(new java.awt.Color(36, 47, 65));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel3.add(panelPrincipal);
        panelPrincipal.setBounds(170, 150, 700, 450);

        jPanel5.setBackground(new java.awt.Color(93, 203, 187));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Esta cuenta fue creada  :");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(170, 100, 700, 40);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
//        this.dispose();
//        this.setVisible(false);
//        new FrmLoging(null, true).setVisible(true);
        this.dispose();
        this.setVisible(false);
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion2ActionPerformed
        panelPrincipal.removeAll();
        panelPrincipal.repaint();
        paneelcoonsolidada.setVisible(true);
    }//GEN-LAST:event_btnSesion2ActionPerformed

    private void btnSesion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion3ActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setVisible(true);
        paneelcoonsolidada.setVisible(false);
        FrmClienteTransferenciaCliente ph = new FrmClienteTransferenciaCliente();
        ph.setSize(690, 500);
        ph.setLocation(8, -40);

        panelPrincipal.removeAll();
        panelPrincipal.add(ph, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnSesion3ActionPerformed

    private void btnSesion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion4ActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setVisible(true);
        paneelcoonsolidada.setVisible(false);
        FrmServicioHistorialCuenta ph = new FrmServicioHistorialCuenta();
        ph.setSize(690, 500);
        ph.setLocation(8, -30);

        panelPrincipal.removeAll();
        panelPrincipal.add(ph, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnSesion4ActionPerformed

    private void btnSesion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSesion5ActionPerformed

    private void btnSesion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSesion6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClientePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnSesion2;
    private rojeru_san.RSButtonRiple btnSesion3;
    private rojeru_san.RSButtonRiple btnSesion4;
    private rojeru_san.RSButtonRiple btnSesion5;
    private rojeru_san.RSButtonRiple btnSesion6;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private javax.swing.JPanel paneelcoonsolidada;
    private javax.swing.JPanel panelBienvenido;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
