/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import controlador.servicio.CuentaBancariaServicio;
import controlador.utilidades.Utilidades;
import modelo.enums.TipoMovimiento;
import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author Usuario
 */
public class FrmClienteTransfer extends javax.swing.JPanel {
 private CuentaBancariaServicio cbs = new CuentaBancariaServicio();
    /**
     * Creates new form NewJPanel
     */
    public FrmClienteTransfer() {
        initComponents();
    }
     private void limpiar() {
        txtCuentaDebi.setText("");
        txtCuentaDep.setText("");
        txtMonto.setText("");
        txtMonto.setText("");
    }

     private void acreditar() {
        String mensaje = "Error se requiere este dato";
        if (!UtilidadesComponente.mostrarError(txtCuentaDebi, mensaje, 'r')
                && !UtilidadesComponente.mostrarError(txtCuentaDep, mensaje, 'r')
                && !UtilidadesComponente.mostrarError(txtMonto, mensaje, 'r')
                && !UtilidadesComponente.mostrarError(txtMonto, mensaje, 'r')) {
            if (cbs.obtenerCuentaBancaria(Integer.parseInt(txtCuentaDebi.getText())) != null) {
                if (cbs.obtenerCuentaBancaria(Integer.parseInt(txtCuentaDep.getText())) != null) {
                    if (cbs.obtenerCuentaBancaria(Integer.parseInt(txtCuentaDebi.getText())).getSaldo() >= Double.parseDouble(txtMonto.getText())) {
                        if (!(txtCuentaDebi.getText().equals(txtCuentaDep.getText()))) {

                            cbs.debitartarCuetna(Double.parseDouble(txtMonto.getText()), cbs, Integer.parseInt(txtCuentaDebi.getText()), TipoMovimiento.TRANSACCION);
                            cbs.acreditarCuetna(Double.parseDouble(txtMonto.getText()), cbs, Integer.parseInt(txtCuentaDep.getText()), TipoMovimiento.TRANSACCION);
                            UtilidadesComponente.mensajeOK("OK", "Se acredito con exito");
                            txtMonto.setText("");

                        } else {
                            UtilidadesComponente.mensajeError("Error", "Error las cuentas son iguales ");
                        }
                    } else {
                        UtilidadesComponente.mensajeError("Error", "Error no cuenta con el dinero suficiente");
                    }
                } else {
                    UtilidadesComponente.mensajeError("Error", "Error la cuenta a depositar no existe ");
                }
            } else {
                UtilidadesComponente.mensajeError("Error", "Error la cuenta a debitar no existe ");
            }

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAsignar = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCuentaDebi = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCuentaDep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnGuardar2 = new rojeru_san.RSButton();
        btnGuardar3 = new rojeru_san.RSButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAsignar.setBackground(new java.awt.Color(36, 47, 65));
        pnlAsignar.setForeground(new java.awt.Color(10, 125, 108));

        jPanel5.setBackground(new java.awt.Color(10, 125, 108));
        jPanel5.setForeground(new java.awt.Color(10, 125, 108));
        jPanel5.setPreferredSize(new java.awt.Dimension(590, 40));
        jPanel5.setRequestFocusEnabled(false);

        labelMetric2.setBackground(new java.awt.Color(40, 153, 255));
        labelMetric2.setText("Transacciones");
        labelMetric2.setColorDeSombra(new java.awt.Color(36, 47, 65));
        labelMetric2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(65, 135, 124));
        jPanel2.setForeground(new java.awt.Color(10, 125, 108));

        jLabel5.setBackground(new java.awt.Color(0, 0, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Imformacion ");

        jLabel6.setBackground(new java.awt.Color(0, 0, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cuenta a debitar :");

        jLabel8.setBackground(new java.awt.Color(0, 0, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monto :");

        txtCuentaDebi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCuentaDebiKeyPressed(evt);
            }
        });

        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMontoKeyPressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCuentaDebi, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCuentaDebi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(10, 125, 108));
        jPanel3.setForeground(new java.awt.Color(10, 125, 108));

        txtCuentaDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCuentaDepKeyPressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel9.setText("Cuenta a depositar :");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Imformacion del destino :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtCuentaDep, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuentaDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(10, 125, 108));
        jPanel6.setPreferredSize(new java.awt.Dimension(590, 40));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        btnGuardar2.setBackground(new java.awt.Color(82, 173, 160));
        btnGuardar2.setText("Acreditar");
        btnGuardar2.setColorHover(new java.awt.Color(223, 247, 244));
        btnGuardar2.setColorText(new java.awt.Color(51, 44, 54));
        btnGuardar2.setColorTextHover(new java.awt.Color(10, 125, 108));
        btnGuardar2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar2);

        btnGuardar3.setBackground(new java.awt.Color(90, 192, 177));
        btnGuardar3.setText("Limpiar");
        btnGuardar3.setColorHover(new java.awt.Color(223, 247, 244));
        btnGuardar3.setColorText(new java.awt.Color(51, 44, 54));
        btnGuardar3.setColorTextHover(new java.awt.Color(10, 125, 108));
        btnGuardar3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnGuardar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar3ActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar3);

        javax.swing.GroupLayout pnlAsignarLayout = new javax.swing.GroupLayout(pnlAsignar);
        pnlAsignar.setLayout(pnlAsignarLayout);
        pnlAsignarLayout.setHorizontalGroup(
            pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );
        pnlAsignarLayout.setVerticalGroup(
            pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsignarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(131, 131, 131))
            .addGroup(pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAsignarLayout.createSequentialGroup()
                    .addGap(373, 373, 373)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE)))
        );

        add(pnlAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        // TODO add your handling code here:
         acreditar();
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnGuardar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar3ActionPerformed
        // TODO add your handling code here:
          limpiar();     
    }//GEN-LAST:event_btnGuardar3ActionPerformed

    private void txtMontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyPressed
        // TODO add your handling code here:
          Utilidades.valiarSoloNumeros(txtMonto);
           Utilidades.LimitarCaracterers(txtMonto, 5);
    }//GEN-LAST:event_txtMontoKeyPressed

    private void txtCuentaDebiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaDebiKeyPressed
        // TODO add your handling code here:
          Utilidades.valiarSoloNumeros(txtCuentaDebi);
           Utilidades.LimitarCaracterers(txtCuentaDebi, 9);
    }//GEN-LAST:event_txtCuentaDebiKeyPressed

    private void txtCuentaDepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaDepKeyPressed
        // TODO add your handling code here:
         Utilidades.valiarSoloNumeros(txtCuentaDep);
          Utilidades.LimitarCaracterers(txtCuentaDep, 9);
    }//GEN-LAST:event_txtCuentaDepKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnGuardar2;
    private rojeru_san.RSButton btnGuardar3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private javax.swing.JPanel pnlAsignar;
    private javax.swing.JTextField txtCuentaDebi;
    private javax.swing.JTextField txtCuentaDep;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
