/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import controlador.servicio.HistorialServicio;
import javax.swing.ButtonGroup;
import vista.tabla.ModeloTablaAccion;

/**
 *
 * @author Usuario
 */
public class FrmHistorialActividad extends javax.swing.JPanel {

    ModeloTablaAccion modelo = new ModeloTablaAccion();
    HistorialServicio hs = new HistorialServicio();

    /**
     * Creates new form FrmHistorialActividad
     */
    public FrmHistorialActividad() {
        initComponents();
        ButtonGroup rd = new ButtonGroup();
        rd.add(dt_todo);
        rd.add(rd_Inicio);
        rd.add(rd_Registros1);
        cargartabla();
    }

    private void cargartabla() {
        modelo.setLista(hs.ListarFecha());
        jTable1.setModel(modelo);
        jTable1.updateUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAsignar = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        rd_Inicio = new javax.swing.JRadioButton();
        dt_todo = new javax.swing.JRadioButton();
        rd_Registros1 = new javax.swing.JRadioButton();

        pnlAsignar.setBackground(new java.awt.Color(36, 47, 65));

        jPanel7.setBackground(new java.awt.Color(65, 135, 124));
        jPanel7.setPreferredSize(new java.awt.Dimension(590, 40));
        jPanel7.setRequestFocusEnabled(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Historial de Acciones");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel3)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(97, 212, 195));
        jPanel3.setLayout(null);

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setForeground(new java.awt.Color(36, 47, 65));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuario", "Accion", "Descripcion", "Fecha"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(223, 247, 244));
        jTable1.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 700, 210);

        jLabel15.setBackground(new java.awt.Color(0, 0, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel15);
        jLabel15.setBounds(130, 70, 170, 10);

        jPanel8.setBackground(new java.awt.Color(65, 135, 124));
        jPanel8.setPreferredSize(new java.awt.Dimension(590, 40));
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setLayout(new java.awt.GridLayout());

        rd_Inicio.setBackground(new java.awt.Color(65, 135, 124));
        rd_Inicio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rd_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        rd_Inicio.setText("        Inicio de Sesion");
        rd_Inicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rd_InicioItemStateChanged(evt);
            }
        });
        rd_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_InicioActionPerformed(evt);
            }
        });
        jPanel8.add(rd_Inicio);

        dt_todo.setBackground(new java.awt.Color(65, 135, 124));
        dt_todo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dt_todo.setForeground(new java.awt.Color(255, 255, 255));
        dt_todo.setSelected(true);
        dt_todo.setText("            Todo");
        dt_todo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dt_todoItemStateChanged(evt);
            }
        });
        dt_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_todoActionPerformed(evt);
            }
        });
        jPanel8.add(dt_todo);

        rd_Registros1.setBackground(new java.awt.Color(65, 135, 124));
        rd_Registros1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        rd_Registros1.setForeground(new java.awt.Color(255, 255, 255));
        rd_Registros1.setText("       Registrode Cuentas");
        rd_Registros1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rd_Registros1ItemStateChanged(evt);
            }
        });
        rd_Registros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_Registros1ActionPerformed(evt);
            }
        });
        jPanel8.add(rd_Registros1);

        javax.swing.GroupLayout pnlAsignarLayout = new javax.swing.GroupLayout(pnlAsignar);
        pnlAsignar.setLayout(pnlAsignarLayout);
        pnlAsignarLayout.setHorizontalGroup(
            pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsignarLayout.createSequentialGroup()
                .addGroup(pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAsignarLayout.setVerticalGroup(
            pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsignarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rd_InicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rd_InicioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_InicioItemStateChanged

    private void rd_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_InicioActionPerformed
        // TODO add your handling code here:
        inicio();
    }//GEN-LAST:event_rd_InicioActionPerformed
    private void inicio() {
        modelo.setLista(hs.listarinicio());
        jTable1.setModel(modelo);
        jTable1.updateUI();

    }

    private void dt_todoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dt_todoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_dt_todoItemStateChanged

    private void dt_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_todoActionPerformed
        // TODO add your handling code here:
        todo();
    }//GEN-LAST:event_dt_todoActionPerformed
    private void todo() {
        modelo.setLista(hs.ListarFecha());
        jTable1.setModel(modelo);
        jTable1.updateUI();

    }     private void cambio() {
        modelo.setLista(hs.cambio());
        jTable1.setModel(modelo);
        jTable1.updateUI();

    }
    private void rd_Registros1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rd_Registros1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_Registros1ItemStateChanged

    private void rd_Registros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_Registros1ActionPerformed
        // TODO add your handling code here:
        registro();
    }//GEN-LAST:event_rd_Registros1ActionPerformed
    private void registro() {
        modelo.setLista(hs.listasregistro());
        jTable1.setModel(modelo);
        jTable1.updateUI();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton dt_todo;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlAsignar;
    private javax.swing.JRadioButton rd_Inicio;
    private javax.swing.JRadioButton rd_Registros1;
    // End of variables declaration//GEN-END:variables

}
