/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import controlador.servicio.CuentaServicio;
import controlador.utilidades.Sesion;
import controlador.utilidades.Utilidades;
import java.awt.Color;
import vista.utilidades.UtilidadesComponente;
import vista.utilidades.Utilitario;

/**
 *
 * @author Usuario
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        jPanel3 .setBackground(new Color(0,0,0,140));
    }
    private void inicioSesion() {
        if (!(txtPassword.getText().equals("")||txtUser.getText().equals(""))) {
            Sesion.setCuenta(new CuentaServicio().inicioSesion(txtUser.getText(), new String(txtPassword.getPassword())));
          String accion="Inicio de sesion";
            if (Sesion.getCuenta() != null) {
                if (Sesion.getCuenta().getEstado() == true) {
                    if (Sesion.getCuenta().getPersona().getRol().getId() == 1) {
                        dispose();
                        new FrmAdministradorPrincipal().setVisible(true);
                        
                    } else {
                        if (Sesion.getCuenta().getPersona().getRol().getId() == 2) {
                            dispose();
                            new FrmServicioPrincipal().setVisible(true);
                        } else {
                            if (Sesion.getCuenta().getPersona().getRol().getId() == 3) {
                                dispose();
                                new FrmCajeroPrincipal().setVisible(true);
                            } else {
                                if (Sesion.getCuenta().getPersona().getRol().getId() == 4) {
                                    dispose();
                                    new FrmClientePrincipal().setVisible(true);
                                }
                            }
                        }
                    }
                } else {
                    Utilitario.mensajeError("Error", "Lo sentimos, el usuario se encuentra actuamente inactivo.");
                }
                Utilidades.guardarHistoriAL(accion, "Ha iniciado sesion " + " " +Sesion.getCuenta().getPersona().getRol().getNombre()+
                                " " +Sesion.getCuenta().getPersona().getId(),"inicio");
            } else {
                Utilitario.mensajeError("Error", "El usuario o la contraseña no son válidos");
            }
        }else{ UtilidadesComponente.mensajeError("Atencion", "Hay campos vacios");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtUser = new rojeru_san.RSMTextFull();
        txtPassword = new rojeru_san.RSMPassView();
        btnSesion2 = new rojeru_san.RSButtonRiple();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new rojeru_san.RSButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(97, 212, 195));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setBackground(new java.awt.Color(97, 212, 195));
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtUser.setBotonColor(new java.awt.Color(94, 80, 101));
        txtUser.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtUser.setPlaceholder("USUARIO");
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, -1));

        txtPassword.setBackground(new java.awt.Color(97, 212, 195));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("2607anabel2016");
        txtPassword.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtPassword.setBotonColor(new java.awt.Color(94, 80, 101));
        txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtPassword.setPlaceholder("*******");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, -1));

        btnSesion2.setBackground(new java.awt.Color(255, 255, 255));
        btnSesion2.setText("Ingresar");
        btnSesion2.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion2.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel6.setBackground(new java.awt.Color(36, 47, 65));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Inicio Sesion");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-customer-26.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-lock-26.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 30, 40));

        btnBuscar.setBackground(new java.awt.Color(82, 173, 160));
        btnBuscar.setText("Salir");
        btnBuscar.setColorHover(new java.awt.Color(223, 247, 244));
        btnBuscar.setColorText(new java.awt.Color(51, 44, 54));
        btnBuscar.setColorTextHover(new java.awt.Color(10, 125, 108));
        btnBuscar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 550));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        jPanel5.setBackground(new java.awt.Color(36, 47, 65));
        jPanel5.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/2012_04_28_Chicago_Rookery.jpg"))); // NOI18N
        jPanel5.add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 550);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 520, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion2ActionPerformed
        inicioSesion();
    }//GEN-LAST:event_btnSesion2ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
      System.exit(0);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnBuscar;
    private rojeru_san.RSButtonRiple btnSesion2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private rojeru_san.RSMPassView txtPassword;
    private rojeru_san.RSMTextFull txtUser;
    // End of variables declaration//GEN-END:variables
}
