/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import controlador.servicio.CuentaBancariaServicio;
import controlador.utilidades.Utilidades;
import modelo.enums.TipoMovimiento;
import vista.utilidades.UtilidadesComponente;

/**
 *
 * @author Usuario
 */
public class FrmMovimiento extends javax.swing.JPanel {

    private CuentaBancariaServicio cbs = new CuentaBancariaServicio();

    /**
     * Creates new form NewJPanel
     */
    public FrmMovimiento() {
        initComponents();
    }

    private void limpiar() {

        txtMonto.setText(" ");
        txt_cuenta.setText(" ");
    }

    private void depositar() {
        String mensaje = "Error se requiere este dato";
        if (!UtilidadesComponente.mostrarError(txt_cuenta, mensaje, 'r')
                && !UtilidadesComponente.mostrarError(txtMonto, mensaje, 'r')) {
            if (cbs.obtenerCuentaBancaria(Integer.parseInt(txt_cuenta.getText())) != null) {
                cbs.acreditarCuetna(Double.parseDouble(txtMonto.getText()), cbs, Integer.parseInt(txt_cuenta.getText()), TipoMovimiento.DEPOSITO);
                  UtilidadesComponente.mensajeOK("OK", "Se realizo el deposito correctamente");
                  txtMonto.setText("");
            } else {
                UtilidadesComponente.mensajeError("Error", "Error la cuenta a debitar no existe ");
            }
        }
    }

    private void retiro() {
        String mensaje = "Error se requiere este dato";
        if (!UtilidadesComponente.mostrarError(txt_cuenta, mensaje, 'r')
                && !UtilidadesComponente.mostrarError(txtMonto, mensaje, 'r')) {
            if (cbs.obtenerCuentaBancaria(Integer.parseInt(txt_cuenta.getText())) != null) {
                if (cbs.obtenerCuentaBancaria(Integer.parseInt(txt_cuenta.getText())).getSaldo() >= Double.parseDouble(txtMonto.getText())) {
                    cbs.debitartarCuetna(Double.parseDouble(txtMonto.getText()), cbs, Integer.parseInt(txt_cuenta.getText()), TipoMovimiento.RETIRO);
                    UtilidadesComponente.mensajeOK("OK", "Se realizo el retiro correctamente");
                    txtMonto.setText("");
                } else {
                    UtilidadesComponente.mensajeError("Error", "Error no cuenta con el dinero suficiente");
                }

            } else {
                UtilidadesComponente.mensajeError("Error", "Error la cuenta a debitar no existe ");
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAsignar = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnGuardar = new rojeru_san.RSButton();
        btnGuardar1 = new rojeru_san.RSButton();
        btnGuardar2 = new rojeru_san.RSButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cuenta = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();

        pnlAsignar.setBackground(new java.awt.Color(36, 47, 65));

        jPanel6.setBackground(new java.awt.Color(10, 125, 108));
        jPanel6.setPreferredSize(new java.awt.Dimension(590, 40));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        btnGuardar.setBackground(new java.awt.Color(82, 173, 160));
        btnGuardar.setText("Retiro");
        btnGuardar.setColorHover(new java.awt.Color(223, 247, 244));
        btnGuardar.setColorText(new java.awt.Color(51, 44, 54));
        btnGuardar.setColorTextHover(new java.awt.Color(10, 125, 108));
        btnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar);

        btnGuardar1.setBackground(new java.awt.Color(90, 192, 177));
        btnGuardar1.setText("Limpiar");
        btnGuardar1.setColorHover(new java.awt.Color(223, 247, 244));
        btnGuardar1.setColorText(new java.awt.Color(51, 44, 54));
        btnGuardar1.setColorTextHover(new java.awt.Color(10, 125, 108));
        btnGuardar1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar1);

        btnGuardar2.setBackground(new java.awt.Color(82, 173, 160));
        btnGuardar2.setText("Deposito");
        btnGuardar2.setColorHover(new java.awt.Color(223, 247, 244));
        btnGuardar2.setColorText(new java.awt.Color(51, 44, 54));
        btnGuardar2.setColorTextHover(new java.awt.Color(10, 125, 108));
        btnGuardar2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar2);

        jPanel2.setBackground(new java.awt.Color(65, 135, 124));

        jLabel5.setBackground(new java.awt.Color(0, 0, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Imformacion ");

        jLabel6.setBackground(new java.awt.Color(0, 0, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero de Cuenta");

        jLabel8.setBackground(new java.awt.Color(0, 0, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monto :");

        txt_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cuentaKeyPressed(evt);
            }
        });

        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMontoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(txtMonto))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(10, 125, 108));
        jPanel5.setPreferredSize(new java.awt.Dimension(590, 40));
        jPanel5.setRequestFocusEnabled(false);

        labelMetric2.setBackground(new java.awt.Color(40, 153, 255));
        labelMetric2.setText("Movimientos de Cuenta");
        labelMetric2.setColorDeSombra(new java.awt.Color(36, 47, 65));
        labelMetric2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAsignarLayout = new javax.swing.GroupLayout(pnlAsignar);
        pnlAsignar.setLayout(pnlAsignarLayout);
        pnlAsignarLayout.setHorizontalGroup(
            pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        pnlAsignarLayout.setVerticalGroup(
            pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsignarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        retiro();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        // TODO add your handling code here:
        depositar();
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void txtMontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyPressed
        // TODO add your handling code here:
        Utilidades.valiarSoloNumeros(txtMonto);
        Utilidades.LimitarCaracterers(txtMonto, 5);

        
    }//GEN-LAST:event_txtMontoKeyPressed

    private void txt_cuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cuentaKeyPressed
        // TODO add your handling code here:
        Utilidades.valiarSoloNumeros(txt_cuenta);
        Utilidades.LimitarCaracterers(txt_cuenta, 9);
    }//GEN-LAST:event_txt_cuentaKeyPressed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtMontoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnGuardar;
    private rojeru_san.RSButton btnGuardar1;
    private rojeru_san.RSButton btnGuardar2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private javax.swing.JPanel pnlAsignar;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txt_cuenta;
    // End of variables declaration//GEN-END:variables
}
