/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import controlador.utilidades.Sesion;
import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class FrmServicioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmServicioPrincipal() {
        initComponents();
        //jPanel3 .setBackground(new Color(0,0,0,140));
        jLabel7.setText(Sesion.getCuenta().getPersona().getApellido() + " " + Sesion.getCuenta().getPersona().getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnSesion2 = new rojeru_san.RSButtonRiple();
        btnSesion3 = new rojeru_san.RSButtonRiple();
        btnSesion4 = new rojeru_san.RSButtonRiple();
        btnSesion5 = new rojeru_san.RSButtonRiple();
        jLabel1 = new javax.swing.JLabel();
        panelBienvenido = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        jButton11 = new javax.swing.JButton();
        pnlAsignar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));

        jPanel2.setBackground(new java.awt.Color(10, 125, 108));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(93, 203, 187));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        btnSesion2.setBackground(new java.awt.Color(223, 247, 244));
        btnSesion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-home-page-24.png"))); // NOI18N
        btnSesion2.setText("Principal");
        btnSesion2.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion2.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSesion2);

        btnSesion3.setBackground(new java.awt.Color(223, 247, 244));
        btnSesion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-add-user-male-26.png"))); // NOI18N
        btnSesion3.setText("Registro");
        btnSesion3.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion3.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnSesion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion3ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSesion3);

        btnSesion4.setBackground(new java.awt.Color(223, 247, 244));
        btnSesion4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-help-30.png"))); // NOI18N
        btnSesion4.setText("Consulta");
        btnSesion4.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion4.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnSesion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion4ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSesion4);

        btnSesion5.setBackground(new java.awt.Color(223, 247, 244));
        btnSesion5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-delete-30.png"))); // NOI18N
        btnSesion5.setText("   Salir");
        btnSesion5.setColorHover(new java.awt.Color(94, 80, 101));
        btnSesion5.setColorText(new java.awt.Color(51, 44, 54));
        btnSesion5.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        btnSesion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion5ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSesion5);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/vinilo-decorativo-arbol-sin-hojas.jpg"))); // NOI18N
        jPanel4.add(jLabel1);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 570));

        panelBienvenido.setBackground(new java.awt.Color(65, 135, 124));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Auquilla jorge");

        labelMetric2.setBackground(new java.awt.Color(40, 153, 255));
        labelMetric2.setText("Bienvenido Empleado: ");
        labelMetric2.setColorDeSombra(new java.awt.Color(40, 52, 71));
        labelMetric2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N

        javax.swing.GroupLayout panelBienvenidoLayout = new javax.swing.GroupLayout(panelBienvenido);
        panelBienvenido.setLayout(panelBienvenidoLayout);
        panelBienvenidoLayout.setHorizontalGroup(
            panelBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBienvenidoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBienvenidoLayout.setVerticalGroup(
            panelBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBienvenidoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton11.setBackground(new java.awt.Color(84, 178, 164));
        jButton11.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton11.setForeground(new java.awt.Color(102, 102, 102));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8-logout-rounded-up-16.png"))); // NOI18N
        jButton11.setText("Cerrar Sesion");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        pnlAsignar.setBackground(new java.awt.Color(40, 52, 71));

        javax.swing.GroupLayout pnlAsignarLayout = new javax.swing.GroupLayout(pnlAsignar);
        pnlAsignar.setLayout(pnlAsignarLayout);
        pnlAsignarLayout.setHorizontalGroup(
            pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        pnlAsignarLayout.setVerticalGroup(
            pnlAsignarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBienvenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton11)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
//        this.dispose();
//        this.setVisible(false);
//        new FrmLoging(null, true).setVisible(true);
this.dispose();
        this.setVisible(false);
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion2ActionPerformed
        pnlAsignar.removeAll();
        pnlAsignar.repaint(); 
    }//GEN-LAST:event_btnSesion2ActionPerformed

    private void btnSesion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion3ActionPerformed
        // TODO add your handling code here:
        pnlAsignar.setVisible(true);
        //panelBienvenido.setVisible(false);
        FrmServicioRegistros ph = new FrmServicioRegistros();
        ph.setSize(690, 600);
        ph.setLocation(5, -30);

        pnlAsignar.removeAll();
        pnlAsignar.add(ph, BorderLayout.CENTER);
        pnlAsignar.revalidate();
        pnlAsignar.repaint();
        
        
    }//GEN-LAST:event_btnSesion3ActionPerformed

    private void btnSesion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion4ActionPerformed
        // TODO add your handling code here: pnlAsignar.setVisible(true);
        // panelBienvenido.setVisible(false);
        FrmHistorialBusqueda ph = new FrmHistorialBusqueda();

        ph.setSize(690, 500);
        ph.setLocation(8, -30);

        pnlAsignar.removeAll();
        pnlAsignar.add(ph, BorderLayout.CENTER);
        pnlAsignar.revalidate();
        pnlAsignar.repaint();
        
        
    }//GEN-LAST:event_btnSesion4ActionPerformed

    private void btnSesion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion5ActionPerformed
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_btnSesion5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmServicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmServicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmServicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmServicioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmServicioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnSesion2;
    private rojeru_san.RSButtonRiple btnSesion3;
    private rojeru_san.RSButtonRiple btnSesion4;
    private rojeru_san.RSButtonRiple btnSesion5;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private javax.swing.JPanel panelBienvenido;
    private javax.swing.JPanel pnlAsignar;
    // End of variables declaration//GEN-END:variables
}
